import React, { useState } from 'react';
import { Weapon, WeaponCategory, Rarity, RegionName, JOURNEY_REGION_ORDER } from '../types';
import { X, Save, Trash2, Sparkles, Sword } from 'lucide-react';
import { ImageInput } from './ImageInput';

interface WeaponEditModalProps {
  weapon?: Weapon | null;
  isOpen: boolean;
  onClose: () => void;
  onSave: (wpn: Weapon) => void;
  onDelete?: (id: string) => void;
}

const WEAPON_TEMPLATES = [
  {
    name: '5★ Signature Sword',
    desc: 'High base ATK, CRIT DMG & elemental buff',
    data: {
      type: 'Sword' as WeaponCategory,
      rarity: 5 as Rarity,
      baseAtk: 608,
      subStatType: 'CRIT DMG',
      subStatValue: '66.2%',
      passiveName: 'Radiant Edge of the Apex',
      passiveDescription: 'Gain 12% All Elemental DMG Bonus. When Elemental Skill hits opponents, gain 1 stack of Resolute Edge for 10s (max 3 stacks), increasing ATK by 8% and Normal Attack DMG by 10%.',
      refinementBonus: 'At R5: 24% Elemental DMG Bonus; stacks increase ATK by 16% and Normal Attack by 20%.',
      source: 'Epitome Invocation (Gacha)',
      region: 'Natlan' as RegionName,
    }
  },
  {
    name: '5★ Heavy Claymore',
    desc: 'Massive CRIT Rate & burst devastation',
    data: {
      type: 'Claymore' as WeaponCategory,
      rarity: 5 as Rarity,
      baseAtk: 674,
      subStatType: 'CRIT Rate',
      subStatValue: '22.1%',
      passiveName: 'Mountain Sovereign\'s Might',
      passiveDescription: 'After triggering an Elemental Reaction, Elemental Skill and Burst DMG is increased by 20% for 12s. Furthermore, the wielder gains 16% Max HP.',
      refinementBonus: 'At R5: Skill and Burst DMG increased by 40%; HP increased by 32%.',
      source: 'Epitome Invocation (Gacha)',
      region: 'Natlan' as RegionName,
    }
  },
  {
    name: '4★ Support Polearm (F2P)',
    desc: 'Energy Recharge & team particle generation',
    data: {
      type: 'Polearm' as WeaponCategory,
      rarity: 4 as Rarity,
      baseAtk: 510,
      subStatType: 'Energy Recharge',
      subStatValue: '45.9%',
      passiveName: 'Windward Resonance',
      passiveDescription: 'Increases Elemental Burst CRIT Rate by 12% and Burst DMG by 32%. Energy particles generated by the wielder restore 3 additional energy to off-field party members.',
      refinementBonus: 'At R5: Burst CRIT Rate by 16%, Burst DMG by 40%.',
      source: 'Fishing Association / Event Reward',
      region: 'Fontaine' as RegionName,
    }
  },
  {
    name: '5★ Catalyst DPS',
    desc: 'Elemental Mastery & cascading reaction boost',
    data: {
      type: 'Catalyst' as WeaponCategory,
      rarity: 5 as Rarity,
      baseAtk: 542,
      subStatType: 'Elemental Mastery',
      subStatValue: '265',
      passiveName: 'Thousand Dreams of Antiquity',
      passiveDescription: 'Party members with the same Elemental Type grant the wielder 32 EM. Party members with different types grant 10% Elemental DMG Bonus. All nearby allies gain 40 EM.',
      refinementBonus: 'At R5: 64 EM per same type; 20% DMG per different type; allies gain 80 EM.',
      source: 'Epitome Invocation (Gacha)',
      region: 'Sumeru' as RegionName,
    }
  }
];

const DEFAULT_EMPTY_WEAPON: Weapon = {
  id: '',
  name: '',
  type: 'Sword',
  rarity: 5,
  baseAtk: 608,
  subStatType: 'CRIT DMG',
  subStatValue: '66.2%',
  passiveName: 'Ancient Blessing',
  passiveDescription: 'Increases all Elemental DMG Bonus by 12%. When Normal/Skill attacks hit opponents, gains additional bonus effects.',
  refinementBonus: 'At R5: Increases all Elemental DMG Bonus by 24%.',
  iconUrl: 'https://enka.network/ui/UI_EquipIcon_Sword_Narukami.png',
  region: 'Natlan',
  source: 'Epitome Invocation (Gacha)',
  description: 'An ancient weapon forged with supreme craftsmanship.'
};

export const WeaponEditModal: React.FC<WeaponEditModalProps> = ({
  weapon,
  isOpen,
  onClose,
  onSave,
  onDelete,
}) => {
  if (!isOpen) return null;

  const isEditing = Boolean(weapon);
  const [formData, setFormData] = useState<Weapon>(
    weapon ? JSON.parse(JSON.stringify(weapon)) : {
      ...DEFAULT_EMPTY_WEAPON,
      id: `wpn-${Date.now()}`
    }
  );

  const applyTemplate = (t: typeof WEAPON_TEMPLATES[0]) => {
    setFormData(prev => ({
      ...prev,
      type: t.data.type,
      rarity: t.data.rarity,
      baseAtk: t.data.baseAtk,
      subStatType: t.data.subStatType,
      subStatValue: t.data.subStatValue,
      passiveName: t.data.passiveName,
      passiveDescription: t.data.passiveDescription,
      refinementBonus: t.data.refinementBonus,
      source: t.data.source,
      region: t.data.region,
    }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.name.trim()) {
      alert('Please enter a valid weapon name');
      return;
    }
    onSave(formData);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/80 backdrop-blur-sm overflow-y-auto">
      <div className="relative w-full max-w-2xl bg-slate-900 border border-slate-700 rounded-2xl shadow-2xl overflow-hidden my-auto max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="p-4 sm:p-5 border-b border-slate-800 bg-slate-950 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sword className="w-5 h-5 text-amber-400" />
            <div>
              <h3 className="font-display font-bold text-lg text-amber-300">
                {isEditing ? `Update Weapon: ${weapon?.name}` : 'Add New Weapon to Archive'}
              </h3>
              <p className="text-xs text-slate-400">
                Configure base attack, refinement bonuses, passives, and origin.
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Quick Starter Templates */}
        <div className="border-b border-slate-800/80 bg-slate-950/40 p-3 sm:p-4">
          <div className="flex items-center gap-1.5 text-xs font-semibold text-amber-400 mb-2">
            <Sparkles className="w-3.5 h-3.5" />
            <span>Quick Starter Templates</span>
            <span className="text-[11px] text-slate-500 font-normal ml-1">(Fills stats, passive & scaling)</span>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
            {WEAPON_TEMPLATES.map((tmpl) => (
              <button
                key={tmpl.name}
                type="button"
                onClick={() => applyTemplate(tmpl)}
                className="rounded-lg border border-slate-800 bg-slate-900/90 p-2 text-left hover:border-amber-500/50 hover:bg-amber-500/5 transition-all text-xs group"
              >
                <div className="font-semibold text-slate-200 group-hover:text-amber-300 truncate">
                  {tmpl.name}
                </div>
                <div className="text-[10px] text-slate-400 truncate mt-0.5">
                  {tmpl.desc}
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Form Body */}
        <form onSubmit={handleSubmit} className="p-4 sm:p-6 overflow-y-auto space-y-4 flex-1 text-xs">
          {/* Row 1: Name and Source */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label className="block text-slate-400 mb-1 font-medium">Weapon Name *</label>
              <input
                type="text"
                required
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2 text-slate-200 focus:outline-none focus:border-amber-400"
                placeholder="e.g. Mistsplitter Reforged"
              />
            </div>
            <div>
              <label className="block text-slate-400 mb-1 font-medium">Source / Acquisition</label>
              <input
                type="text"
                value={formData.source}
                onChange={(e) => setFormData({ ...formData, source: e.target.value })}
                className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2 text-slate-200 focus:outline-none focus:border-amber-400"
                placeholder="e.g. Weapon Event Wish, Blacksmith..."
              />
            </div>
          </div>

          {/* Row 2: Type, Rarity, Region */}
          <div className="grid grid-cols-3 gap-3">
            <div>
              <label className="block text-slate-400 mb-1 font-medium">Weapon Type</label>
              <select
                value={formData.type}
                onChange={(e) => setFormData({ ...formData, type: e.target.value as WeaponCategory })}
                className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2 text-slate-200 focus:outline-none focus:border-amber-400"
              >
                {['Sword', 'Claymore', 'Polearm', 'Bow', 'Catalyst'].map((t) => (
                  <option key={t} value={t}>{t}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-slate-400 mb-1 font-medium">Rarity</label>
              <select
                value={formData.rarity}
                onChange={(e) => setFormData({ ...formData, rarity: Number(e.target.value) as Rarity })}
                className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2 text-slate-200 focus:outline-none focus:border-amber-400"
              >
                {[5, 4, 3, 2, 1].map((r) => (
                  <option key={r} value={r}>{r}-Star</option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-slate-400 mb-1 font-medium">Origin Nation / Region</label>
              <select
                value={formData.region || 'Mondstadt'}
                onChange={(e) => setFormData({ ...formData, region: e.target.value as RegionName })}
                className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2 text-slate-200 focus:outline-none focus:border-amber-400"
              >
                {JOURNEY_REGION_ORDER.map((reg) => (
                  <option key={reg} value={reg}>{reg}</option>
                ))}
              </select>
            </div>
          </div>

          {/* Row 3: Stats (Base ATK, Sub-stat type & value) */}
          <div className="p-3 bg-slate-950/80 rounded-xl border border-slate-800 space-y-2">
            <span className="text-amber-400 font-bold block">Level 90 Stats</span>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div>
                <label className="block text-slate-500 text-[11px]">Base ATK</label>
                <input
                  type="number"
                  value={formData.baseAtk}
                  onChange={(e) => setFormData({ ...formData, baseAtk: Number(e.target.value) })}
                  className="w-full bg-slate-900 border border-slate-700 rounded p-1.5 text-slate-200"
                />
              </div>
              <div>
                <label className="block text-slate-500 text-[11px]">Sub-stat Type</label>
                <select
                  value={
                    ['CRIT DMG', 'CRIT Rate', 'ATK%', 'Energy Recharge', 'Elemental Mastery', 'HP%', 'DEF%', 'Physical DMG Bonus', 'None'].includes(formData.subStatType)
                      ? formData.subStatType
                      : 'Custom'
                  }
                  onChange={(e) => {
                    const val = e.target.value;
                    if (val !== 'Custom') {
                      setFormData({ ...formData, subStatType: val });
                    }
                  }}
                  className="w-full bg-slate-900 border border-slate-700 rounded p-1.5 text-slate-200 focus:border-amber-400 focus:outline-none"
                >
                  <option value="CRIT DMG">CRIT DMG</option>
                  <option value="CRIT Rate">CRIT Rate</option>
                  <option value="ATK%">ATK%</option>
                  <option value="Energy Recharge">Energy Recharge</option>
                  <option value="Elemental Mastery">Elemental Mastery</option>
                  <option value="HP%">HP%</option>
                  <option value="DEF%">DEF%</option>
                  <option value="Physical DMG Bonus">Physical DMG Bonus</option>
                  <option value="None">None (1★/2★)</option>
                  <option value="Custom">+ Custom Stat...</option>
                </select>
                {!['CRIT DMG', 'CRIT Rate', 'ATK%', 'Energy Recharge', 'Elemental Mastery', 'HP%', 'DEF%', 'Physical DMG Bonus', 'None'].includes(formData.subStatType) && (
                  <input
                    type="text"
                    value={formData.subStatType}
                    onChange={(e) => setFormData({ ...formData, subStatType: e.target.value })}
                    className="mt-1 w-full bg-slate-900 border border-slate-700 rounded p-1 text-slate-200 text-xs"
                    placeholder="Enter custom stat..."
                  />
                )}
              </div>
              <div>
                <label className="block text-slate-500 text-[11px]">Sub-stat Value</label>
                <input
                  type="text"
                  value={formData.subStatValue}
                  onChange={(e) => setFormData({ ...formData, subStatValue: e.target.value })}
                  className="w-full bg-slate-900 border border-slate-700 rounded p-1.5 text-slate-200"
                  placeholder="e.g. 66.2%"
                />
              </div>
            </div>
          </div>

          {/* Weapon Icon ImageInput (URL or File Upload) */}
          <ImageInput
            label="Weapon Icon"
            value={formData.iconUrl}
            onChange={(url) => setFormData({ ...formData, iconUrl: url })}
            aspectRatio="square"
            placeholder="Paste weapon icon URL or upload local image..."
            helperText="Square weapon icon used for inventory list and detail display."
          />

          {/* Passive Name and Description */}
          <div className="space-y-3">
            <div>
              <label className="block text-slate-400 mb-1 font-medium">Passive Ability Name</label>
              <input
                type="text"
                value={formData.passiveName}
                onChange={(e) => setFormData({ ...formData, passiveName: e.target.value })}
                className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2 text-slate-200 focus:outline-none focus:border-amber-400"
                placeholder="e.g. Mistsplitter's Edge"
              />
            </div>
            <div>
              <label className="block text-slate-400 mb-1 font-medium">Passive Description (R1)</label>
              <textarea
                rows={3}
                value={formData.passiveDescription}
                onChange={(e) => setFormData({ ...formData, passiveDescription: e.target.value })}
                className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2 text-slate-200 focus:outline-none focus:border-amber-400"
              />
            </div>
            <div>
              <label className="block text-slate-400 mb-1 font-medium">Refinement Scaling (R5 Bonus)</label>
              <input
                type="text"
                value={formData.refinementBonus || ''}
                onChange={(e) => setFormData({ ...formData, refinementBonus: e.target.value })}
                className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2 text-slate-200 focus:outline-none focus:border-amber-400"
                placeholder="e.g. At R5: Elemental DMG bonus doubled to 24%."
              />
            </div>
          </div>

          {/* Lore Description */}
          <div>
            <label className="block text-slate-400 mb-1 font-medium">Weapon Lore / Flavor Text</label>
            <textarea
              rows={2}
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2 text-slate-200 focus:outline-none focus:border-amber-400"
              placeholder="The history and legend behind this weapon's forging..."
            />
          </div>

          {/* Footer Submit Buttons */}
          <div className="pt-3 border-t border-slate-800 flex items-center justify-between">
            {isEditing && onDelete ? (
              <button
                type="button"
                onClick={() => {
                  if (confirm(`Are you sure you want to delete ${formData.name}?`)) {
                    onDelete(formData.id);
                    onClose();
                  }
                }}
                className="flex items-center gap-1 px-3 py-2 text-rose-400 hover:text-rose-300 hover:bg-rose-500/10 rounded-lg transition-colors"
              >
                <Trash2 className="w-4 h-4" />
                <span>Delete</span>
              </button>
            ) : <div />}

            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 text-slate-400 hover:text-white bg-slate-800 hover:bg-slate-700 rounded-lg transition-colors"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="flex items-center gap-1.5 px-4 py-2 bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 text-slate-950 font-bold rounded-lg shadow transition-all"
              >
                <Save className="w-4 h-4" />
                <span>Save to Archive</span>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};
